// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as View from "../src/components/primitives/View/View.bs.js";
import * as React from "react";
import * as ConsumerPage from "../src/components/consumer/ConsumerPage.bs.js";
import * as ThemeProvider from "../src/contexts/ThemeContext/ThemeProvider.bs.js";

function Index(Props) {
  var theme = React.useContext(ThemeProvider.themeContext);
  return React.createElement(ConsumerPage.make, {
              children: React.createElement(View.make, {
                    children: "home" + theme
                  })
            });
}

var make = Index;

var $$default = Index;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* View Not a pure module */
